---
language: python
services: docker

env:
  global:
    - ROLE_NAME: nomad
  matrix:
    - MOLECULE_DISTRO: debian9

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME allgreed.$ROLE_NAME
  - cd allgreed.$ROLE_NAME

#install:
#  # Install test dependencies.
#  - pip install molecule docker

#script:
#  # Run tests.
#  - molecule test

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
